apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
 name: consumer-scaler
spec:
 scaleTargetRef:
   apiVersion: extensions/v1beta1
   kind: Deployment
   name: consumer
 minReplicas: {{ .Values.minreplicas }}
 maxReplicas: {{ .Values.maxreplicas }}
 metrics:
  - type: External
    external:
      metricName: {{ .Values.externalmetric.name }}
      targetValue: {{ .Values.externalmetric.targetvalue }}

