# Default values for scale-consumer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

queue:
  name: ""

servicebus:
  namespace: ""

resourcegroup:
  name: ""

minreplicas: 1

maxreplicas: 3

externalmetric:
  name: ""
  targetvalue: 10

containerimage: ""

