apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.custom.metrics.k8s.io
spec:
  service:
    name: {{ template "azure-k8s-metrics-adapter.fullname" . }}
    namespace: {{ .Release.Namespace }}
  group: custom.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: {{ .Values.apiServiceInsecureSkipTLSVerify }}
  groupPriorityMinimum: {{ .Values.apiServiceGroupPriorityMinimum }}
  versionPriority: {{ .Values.apiServiceVersionPriority }}
---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.external.metrics.k8s.io
spec:
  service:
    name: {{ template "azure-k8s-metrics-adapter.fullname" . }}
    namespace: {{ .Release.Namespace }}
  group: external.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: {{ .Values.apiServiceInsecureSkipTLSVerify }}
  groupPriorityMinimum: {{ .Values.apiServiceGroupPriorityMinimum }}
  versionPriority: {{ .Values.apiServiceVersionPriority }}
