apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: externalmetrics.azure.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: azure.com
  version: v1alpha2
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: externalmetrics
    singular: externalmetric
    kind: ExternalMetric
    shortNames:
    - aem
  #validation: #Turn on validation in future
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: custommetrics.azure.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: azure.com
  version: v1alpha2
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: custommetrics
    singular: custommetric
    kind: CustomMetric
    shortNames:
    - acm
  #validation: #Turn on validation in future