apiVersion: v1
appVersion: "0.5.0"
description: An implementation of the Kubernetes Custom Metrics API and External Metrics API for Azure Services
name: azure-k8s-metrics-adapter
version: 0.1.0
sources:
  - https://github.com/Azure/azure-k8s-metrics-adapter
